
language: bash
services: docker

install:
  - git clone https://github.com/samejack/docker-elasticsearch-kibana

before_script:
  - image="samejack/elasticsearch-kibana"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
